# Set a plain language title for the site.
title: USWDS Custom Theme Typeface Tokens

# Write a short description for the site. This is used for "meta description."
description: Theme settings for more typefaces from Google Fonts

# Enable for live hosting on GitHub Pages
# This should match the name of your GitHub repository, along with a leading forward slash (/).
# baseurl: /uswds-custom-theme-typeface-tokens

# Set the language for the site. Used for "html lang." Default is English.
lang: en

# Avoid GitHub API authentication when building locally.
github: [metadata]
